### ISSUE TITLE
приклад 

### ISSUE THREAD

**Issue by Muxamedin** [mrich7294/hillel#8]
https://github.com/mrich7294/hillel/blob/cca520610f709bcac471f7a5cdd9e82168de6cf5/hw12/func_3_1_yield.py#L38
Навіть якщо потрібно вивести дані не обовязково збирати дані у список щоб його надрукувати:

1.
for ele in search_number(a, b):
        lst.append(ele)
 print(f'Прості числа в діапазоні {a} - {b}: ', lst)
 
 2.
 print(f'Прості числа в діапазоні {a} - {b}: [ ', end="")
 for ele in search_number(a, b):
        print(ele, end=" ") 
  print(' ]')

**Comment by mrich7294** [comment]
Дякую, прийму до уваги!
