### ISSUE TITLE
Порада 

### ISSUE THREAD

**Issue by Muxamedin** [mrich7294/hillel#9]
https://github.com/mrich7294/hillel/blob/18bad7f408002be908829a428533a1724c0b4d00/hw15/hw_my_package.py#L15
ідея вашої рпограми показати наскільки швидше один алгоритм за інший 
<img width="713" alt="image" src="https://user-images.githubusercontent.com/4419752/206864417-e56c6468-619f-4443-a893-c2c7663dc502.png">
і ми спостерігаємо не велику різницю у швидкості сортування 
Але відбувається наступне :
https://github.com/mrich7294/hillel/blob/18bad7f408002be908829a428533a1724c0b4d00/hw15/hw_my_package.py#L10
тут ви сотируєте список і він уже відсотовний попдає в наступну функцію у якій не відбувається перестановок 
https://github.com/mrich7294/hillel/blob/18bad7f408002be908829a428533a1724c0b4d00/hw15/hw_my_package.py#L15
і також lst попадає в наступну функцію 
https://github.com/mrich7294/hillel/blob/18bad7f408002be908829a428533a1724c0b4d00/hw15/hw_my_package.py#L20

щоб провести справедливий тест пропоную додати наступне 
<img width="561" alt="image" src="https://user-images.githubusercontent.com/4419752/206864588-a06c4451-8942-457b-8a1e-56136f1b472a.png">

<img width="629" alt="image" src="https://user-images.githubusercontent.com/4419752/206864607-3bd5381c-a9a8-4289-99fd-606813af7438.png">
nтоді ми ми можемо побачити різницю в часі - на однаковій послідовності
<img width="698" alt="image" src="https://user-images.githubusercontent.com/4419752/206864640-373dbcd1-a1cb-4bd6-ab07-841a9cbeb284.png">

https://github.com/mrich7294/hillel/blob/18bad7f408002be908829a428533a1724c0b4d00/hw15/hw_my_package.py#L15

**Comment by mrich7294** [comment]
Прийму до уваги!
